###
GET http://localhost:8080/api/users/

###
GET http://localhost:8080/api/categories/

###
GET http://localhost:8080/api/products/ HTTP/1.1

###
POST http://localhost:8080/api/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Electric Iron",
    "price": 50.67,
    "stock": 50
}

###
GET http://localhost:8080/api/orders/

###
GET http://localhost:8080/api/carts/

###
GET http://localhost:8080/api/carts/
Authorization: token 693cdc6d218008003946474589c86cdd3cf40b4e

###
GET http://localhost:8080/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Token ea206c026f44aaaac790420e67e5567926060863

{
    "cart_id": "f79730ec-a786-4d55-bb04-97e2204f2279"
}

###
GET http://localhost:8080/api/carts/1fcf9c54-54b7-4c03-a93f-370203e04f6b/

###
POST http://localhost:8080/api/carts/
Content-Type: application/json

{
    "cart_code": "ABC_577",
    "items": [
        {
            "product": "7e157e94-23d5-47a7-9069-7fcebf75f592",
            "quantity": "6"
        },
        {
            "product": "ccebb85c-514e-4b91-9527-6a10836e9e06",
            "quantity": "2"
        }
    ]
}


###
POST http://localhost:8080/api/carts/
Content-Type: application/json
Authorization: Token 693cdc6d218008003946474589c86cdd3cf40b4e

{
    "items": [
        {
            "product": "camry-2009-xle",
            "quantity": "3"
        }
    ]
}

###
POST http://localhost:8080/api/carts/ HTTP/1.1
Content-Type: application/json
Authorization: Token 693cdc6d218008003946474589c86cdd3cf40b4e

{
    "items": [
        {
            "product": "electric-iron",
            "quantity": "10"
        }
    ]
}

###
PATCH http://localhost:8080/api/carts/f79730ec-a786-4d55-bb04-97e2204f2279/ HTTP/1.1
Content-Type: application/json
Authorization: Token 693cdc6d218008003946474589c86cdd3cf40b4e

{
    "items": [
        {
            "product": "camry-2009-xle",
            "quantity": "8"
        }
    ]
}

###
PATCH http://localhost:8080/api/carts/1fcf9c54-54b7-4c03-a93f-370203e04f6b/ HTTP/1.1
Content-Type: application/json

{
    "items": [
        {
            "product": "",
            "quantity": 8
        },
        {
            "product": "ccebb85c-514e-4b91-9527-6a10836e9e06",
            "quantity": 5
        }
    ]
}

###
GET http://localhost:8080/auth/users/me/ HTTP/1.1
Authorization: token 0aa01237082ccf2c7a58fb2f7cdd1df367d13476

###
POST http://localhost:8080/auth/token/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "adminuser@test.com",
    "password": "test"
}

###
POST http://localhost:8080/auth/token/logout/ HTTP/1.1
Authorization: Token ea206c026f44aaaac790420e67e5567926060863

###
POST http://localhost:8080/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "adminuser@test.com",
    "password": "test"
}

###
POST http://localhost:8080/auth/jwt/logout/ HTTP/1.1
Authorization: Token 0aa01237082ccf2c7a58fb2f7cdd1df367d13476


###
POST http://localhost:8080/api/reviews/ HTTP/1.1
Authorization: Token ea206c026f44aaaac790420e67e5567926060863
Content-Type: application/json

{
    "product": "camry-2009-xle",
    "rating": 4,
    "comment": "This is a really good electric iron. I love it"
}

###
GET http://localhost:8080/api/reviews/ HTTP/1.1

###
DELETE http://localhost:8080/api/reviews/2a1c7979-680d-4729-b5ec-8077e12c03c6/ HTTP/1.1



###
GET http://localhost:8080/api/wishlists/ HTTP/1.1
Authorization: Token ea206c026f44aaaac790420e67e5567926060863


###
POST http://localhost:8080/api/wishlists/ HTTP/1.1
Authorization: Token ea206c026f44aaaac790420e67e5567926060863
Content-Type: application/json

{
    "product": "electric-iron"
}