### CARTS

### List Carts
GET {{host}}/api/carts/
Authorization: Token {{token}}

### Get Cart by ID
GET {{host}}/api/carts/1fcf9c54-54b7-4c03-a93f-370203e04f6b/

### Create Cart
POST {{host}}/api/carts/
Content-Type: application/json
Authorization: Token {{token}}

{
    "cart_code": "ABC_577",
    "items": [
        {
            "product": "7e157e94-23d5-47a7-9069-7fcebf75f592",
            "quantity": "6"
        },
        {
            "product": "ccebb85c-514e-4b91-9527-6a10836e9e06",
            "quantity": "2"
        }
    ]
}

### Add Item to Cart
POST {{host}}/api/carts/
Content-Type: application/json
Authorization: Token {{token}}

{
    "items": [
        {
            "product": "camry-2009-xle",
            "quantity": "3"
        }
    ]
}

### Update Cart
PATCH {{host}}/api/carts/f79730ec-a786-4d55-bb04-97e2204f2279/
Content-Type: application/json
Authorization: Token {{token}}

{
    "items": [
        {
            "product": "camry-2009-xle",
            "quantity": "8"
        }
    ]
}
