### ORDERS

### List Orders
GET {{host}}/api/orders/
Authorization: Token {{token}}

### Get Order with Cart ID
GET {{host}}/api/orders/
Content-Type: application/json
Authorization: Token {{token}}

{
    "cart_id": "f79730ec-a786-4d55-bb04-97e2204f2279"
}
