### PRODUCTS

### List Products
GET {{host}}/api/products/ HTTP/1.1

### Search for products
GET {{host}}/api/products?search=fan HTTP/1.1

### Search for products
GET {{host}}/api/products?name__iexact=fan HTTP/1.1


### Checking for price
GET {{host}}/api/products?min_price=300

### Ordering by price
GET {{host}}/api/products?ordering=-price

### Create Product
POST {{host}}/api/products/
Content-Type: application/json
Authorization: Token {{token}}

{
    "name": "Washing Machine",
    "price": 59,
    "stock": 50,
    "description": "A high-quality electric iron for smooth and wrinkle-free clothes.",
    "categories": ["53fdedb9-aae1-414d-864f-61d0cfbb8612", "08dd0ce9-7f7f-4581-82e6-e126fdaa2f98"]
}
