### REVIEWS

### Create Review
POST {{host}}/api/reviews/
Authorization: Token {{token}}
Content-Type: application/json

{
    "product": "camry-2009-xle",
    "rating": 4,
    "comment": "This is a really good electric iron. I love it"
}

### List Reviews
GET {{host}}/api/reviews/

### Delete Review
DELETE {{host}}/api/reviews/2a1c7979-680d-4729-b5ec-8077e12c03c6/
Authorization: Token {{token}}
